### ISSUE TITLE
GET Product List API

### ISSUE THREAD

**Issue by onepiecepura** [onepiecepura/assignment-java-boot-camp#1]
## Document
https://github.com/onepiecepura/assignment-java-boot-camp/blob/develop/doc/products.md

## Tasks
- [x] Mock product
- [x] Create product entity
- [x]  Create product controller
- [x] Create product repository
- [x] Create product service
- [x] Test product controller
- [x] Test product repository
- [x] Doc Products.md
