### ISSUE TITLE
GET Product Detail API

### ISSUE THREAD

**Issue by onepiecepura** [onepiecepura/assignment-java-boot-camp#3]
## Document
https://github.com/onepiecepura/assignment-java-boot-camp/blob/develop/doc/product-detail.md

## Tasks
- [x]  Add mock product data
- [x] Create product detail model
- [x]  Find product by id
- [x] Test find product by id  controller
- [x] Test find  product by id repository
- [x] Doc products-detail.md
